// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvpbzafhnaauxdlzteza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cGJ6YWZobmFhdXhkbHp0ZXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjg4NDIsImV4cCI6MjA3MTIwNDg0Mn0.lo31JL2lFHRx2_dMrX31_lJ-EbM-DIJ042R7R34uxzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});